hydra:
  output_subdir: ${hydra:runtime.cwd}/../../assets/hydra
  run:
    dir: ${hydra:runtime.cwd}/../../assets/hydra/log

params:
  epochs: 3
  out_channels: 5
  lr: 0.01
  batch_size: 32
  num_workers: 2
  train_share: 0.8
